name: orgatex-smart-factory
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883" # MQTT
      - "9001:9001" # WS
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    # healthcheck:
    #   test: ["CMD-SHELL", "timeout -t 5 mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 10

  dynamodb:
    image: amazon/dynamodb-local:2.5.2
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"] # In-memory for local testing
    ports:
      - "8000:8000"
    healthcheck:
      test: [
          "CMD-SHELL",
          'if [ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]; then exit 0; else exit 1; fi',
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    depends_on:
      dynamodb:
        condition: service_healthy

  processor:
    build:
      context: ./processor
    ports:
      - "8081:8081"
    depends_on:
      dynamodb:
        condition: service_healthy
      # mosquitto:
      #   condition: service_healthy

  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      dynamodb:
        condition: service_healthy
